### ISSUE TITLE
[BUG] Readme pointing to SPFX WebParts navigator

### ISSUE THREAD

**Issue by rjesh-git** [pnp/teams-dev-samples#24]
# Readme.md in the root folder

## Expected or Desired Behavior
The Sample Navigator link should be pointing to [Teams Sample Navigator](http://aka.ms/pnpteams)

## Observed Behavior
The Sample Navigator link is pointing to [https://pnp.github.io/sp-dev-fx-webparts/](https://pnp.github.io/sp-dev-fx-webparts/)

## Steps to Reproduce

1. Go to [https://github.com/pnp/teams-dev-samples] Readme.md
2. Click on 'Sample Navigator'
3. Navigates to SPFX WebParts Navigator

## Context
Created for PR reference

**Comment by BobGerman** [comment]
Good catch thanks veyr much @rjesh-git !
