### ISSUE TITLE
Include Tab SSO Sample

### ISSUE THREAD

**Issue by HiltonGiesenow** [pnp/teams-dev-samples#36]
It would be great to have a Teams Tabs SSO sample included in here. One already exists at https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs, but this project is a great, consolidated resource so it should be included here rather. I'd be happy to assist in any way, and if it's useful I have a dotnet port of this node sample, inside https://github.com/HiltonGiesenow/msteams-tabs-sso-sample-nodejs

**Comment by BobGerman** [comment]
Great input thanks!
It would be awesome to have a C# version of the SSO sample; please do submit it! Maybe you'd also be interested in demonstrating it on a community call?

BTW for a consolidated view of samples across both the PnP community and Microsoft, please check out http://aka.ms/TeamsSampleBrowser ... it has all the same samples plus a way to select the scenario and technology you're looking for.

Thanks!

**Comment by HiltonGiesenow** [comment]
I'd be delighted on both accounts! I'm definitely not an expert in SSO/MSAL/etc., but more than happy to take a stab and will get started on it straight away this weekend.

Thanks for the info on the sample browser - it's absolutely got some great stuff in there, but I actually find the tiled view quite distracting, and I'm probably not the only one. Is there any chance to get a "tabular" view in some way?

**Comment by HiltonGiesenow** [comment]
@BobGerman , I'd be happy to put together both a node and a dotnet version, but how would we structure these. I see for instance the "tab-aad-msal2" sample is node only. Should we indicate in the sample name which platform is used (e.g. tab-aad-msal2-node)? Alternatively, should the samples aim to include both (e.g. tab-aad-msal2/node and tab-aad-msal2/dotnet)? If so, the existing samples should ideally be extended too. What do you think?

**Comment by HiltonGiesenow** [comment]
@BobGerman I've started on this and I've completed a dotnet version (code complete). It's updated from the originals I referenced above to use MSAL 2.0 instead of ADAL. I'm still working on the documentation (readme), and I'd like to put a node/react version together, but the dotnet one I think is in reasonable shape if you'd like to take a look. It's at https://github.com/HiltonGiesenow/teams-dev-samples/tree/add-tabs-sso-sample/samples/tab-sso

**Comment by HiltonGiesenow** [comment]
If anyone's following this thread, just fyi that I'm waiting for the latest version of the Teams Toolkit to release, as it includes a LOT of out of the box setup for this using Node - I want to use that as a baseline for the Node version of the sample (the release was slightly delayed for the latest version, I've been informed)

**Comment by mmsharepoint** [comment]
Just submitted a sample using not only SSO but also the on-behalf flow for generating an access token.
#39

**Comment by HiltonGiesenow** [comment]
@mmsharepoint , I'm not clear why you've built another sample for this - please read the comments above. I've BUILT the sample already a few weeks ago, as I stated, but only for dotnet so far. I'm waiting for the latest Teams Toolkit to release, to build a node sample, as it already includes most of the required steps (as you know). I want to modify it slightly to include some of the additional things that I put into the dotnet sample, but don't want people to have to start from scratch, if they're choosing to use   the Teams toolkit.

**Comment by mmsharepoint** [comment]
Sorry for the misunderstanding. I did not build it to address THIS issue, you can still go on with your work and by using the Teams Toolkit it will be still kind of unique. No worries

**Comment by HiltonGiesenow** [comment]
No worries, just wanted to make sure we weren't duplicating effort unnecessarily. Would be much appreciated if you'd like to glance over the dotnet one, and see if you think there's anything missing/worth adding/emphasising

**Comment by BobGerman** [comment]
All good. Nobody ever said, "We have too many great samples". Thank you guys. I'm working on your PR now @HiltonGiesenow; thanks!

**Comment by HiltonGiesenow** [comment]
@BobGerman I guess we can close this 'issue' now, with the sample complete. Thanks for letting me contribute to this great project. Let me know if you're still interested in having me demo any of it on a community call, more than happy to do so.
