### ISSUE TITLE
[SUGGESTION] App virtual events meeting extensibility docs improvements

### ISSUE THREAD

**Issue by DomWill** [pnp/teams-dev-samples#57]
The docs for the following sample are difficult to follow due to gaps in the documentation https://github.com/pnp/teams-dev-samples/tree/master/samples/app-virtual-events-meeting-extensibility#create-microsoft-teams-meeting-with-calling--meeting-bot-and-add-a-custom-app-to-the-meeting-programmatically--sample-code 

**Request 1:**
Step 3.4 
![image](https://user-images.githubusercontent.com/20867028/104686057-2da54600-5748-11eb-9829-bc76e1f4bf33.png)
Where do the COSMOS DB details come from? The previous docs do not setup a DB. If they are not needed it should be said clearly in the documentation. 

**Request 2**
Step 4 is lacking details how to upload the app package into Teams. It does not explain to switch the client to Dev Preview which is required by the app manifest. 
Also step 4 does not detail how to run the service. Example from another Teams sample https://github.com/OfficeDev/microsoft-teams-sample-meetings-token#step-4-build-and-run-the-service

**Comment by arun-msft** [comment]
@DomWill : I will check this and will update you.

**Comment by arun-msft** [comment]
@DomWill :  Thanks for your feedback. Updated the readme file and manifest file.

**Comment by BobGerman** [comment]
Docs gave been updated; thanks all!
