### ISSUE TITLE
What value to put in the TeamsServiceUrl for bot-b2c-chat-bot?

### ISSUE THREAD

**Issue by tinsheep** [pnp/teams-dev-samples#77]
## Sample (which sample are you talking about)
bot-b2c-chat-bot

## Authors

@Saikrishna-MSFT 
@arun-msft 

## Question (the more details, the better)
Hi- thanks for the sample.  I'm not sure what to put for the "TeamsServiceUrl" in the appsetting.json.
If i put my bot ngrok endpoint i get 404's
If i put https://webchat.botframework.com/ i get 403's
but either way i get an exception when i call await connectorClient.Conversations.CreateConversationAsync(parameters);
in the WebChatBot.cs.
Thanks for any guidance.

## Question
What value to put in the TeamsServiceUrl for bot-b2c-chat-bot

**Comment by Saikrishna-MSFT** [comment]
Hi @tinsheep ,

This Url is sent by Teams in the Bot payload in the turnContext.Activity.serviceUrl property. You may debug the project to get this URL. 

Please let us know if there is any issue. Thanks.

**Comment by tinsheep** [comment]
Thanks for the help - got it working
